In [1]:
import numpy as np

In [2]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [3]:
sample_matrix[1,2]

21

In [4]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [5]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

### Selection techniques

In [6]:
sample_array=np.arange(1,20)

In [7]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [9]:
np.exp(sample_array)     #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [10]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [11]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [12]:
np.max(sample_array)

19

In [13]:
np.min(sample_array)

1

In [14]:
np.argmax(sample_array)

18

In [15]:
np.argmin(sample_array)

0

In [17]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [18]:
np.var(sample_array)

30.0

In [20]:
np.std(sample_array)

5.477225575051661

In [21]:
np.mean(sample_array)

10.0

In [23]:
array=np.random.randn(3,4)
array

array([[-0.52587509,  1.47308844,  0.10905526,  0.91567153],
       [-1.0646872 ,  3.11851926,  0.31100902, -0.28268596],
       [-1.79005645,  2.00805206, -1.0462669 , -0.1440507 ]])

In [24]:
np.round(array,decimals=2)

array([[-0.53,  1.47,  0.11,  0.92],
       [-1.06,  3.12,  0.31, -0.28],
       [-1.79,  2.01, -1.05, -0.14]])

In [26]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

### Pandas

In [28]:
import pandas as pd
import numpy as np

### Pandas dataframe and indexing

In [29]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [30]:
sports1['football']

2

In [31]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [33]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [34]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.650311  0.104882  0.764471  0.652310  0.956218
B  0.447261  0.699253  0.457481  0.467062  0.769417
C  0.656240  0.038028  0.723761  0.945846  0.476240
D  0.855869  0.692492  0.871529  0.891666  0.350260
E  0.166118  0.249081  0.975338  0.904686  0.598162
F  0.350848  0.823409  0.059711  0.094319  0.974632
G  0.431278  0.762665  0.831820  0.898979  0.928867
H  0.697228  0.333557  0.064233  0.000648  0.377747

In [37]:
df1["Score1"]

A    0.650311
B    0.447261
C    0.656240
D    0.855869
E    0.166118
F    0.350848
G    0.431278
H    0.697228
Name: Score1, dtype: float64

In [38]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.650311  0.104882
B  0.447261  0.699253
C  0.656240  0.038028
D  0.855869  0.692492
E  0.166118  0.249081
F  0.350848  0.823409
G  0.431278  0.762665
H  0.697228  0.333557

In [39]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.650311  0.104882  0.764471  0.652310  0.956218  0.755194
B  0.447261  0.699253  0.457481  0.467062  0.769417  1.146514
C  0.656240  0.038028  0.723761  0.945846  0.476240  0.694267
D  0.855869  0.692492  0.871529  0.891666  0.350260  1.548361
E  0.166118  0.249081  0.975338  0.904686  0.598162  0.415200
F  0.350848  0.823409  0.059711  0.094319  0.974632  1.174258
G  0.431278  0.762665  0.831820  0.898979  0.928867  1.193943
H  0.697228  0.333557  0.064233  0.000648  0.377747  1.030784

In [40]:
df2={'ID':['101','102','103','107'],'NAME':['JOHN','MERCY','AMIT','KAVIN'],'PROFIT':[20,54,56,87]}
df=pd.DataFrame(df2)
df

ID   NAME  PROFIT
0  101   JOHN      20
1  102  MERCY      54
2  103   AMIT      56
3  107  KAVIN      87

In [41]:
df["ID"]

0    101
1    102
2    103
3    107
Name: ID, dtype: object

In [42]:
df.drop(3)

ID   NAME  PROFIT
0  101   JOHN      20
1  102  MERCY      54
2  103   AMIT      56

KeyError: "['ID'] not found in axis"